import React, { useRef } from 'react';
import { motion } from 'framer-motion';
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import ScoreGauge from './ScoreGauge';
import { 
  Download, 
  RotateCcw, 
  Scale, 
  CheckCircle2,
  AlertCircle,
  Equal
} from 'lucide-react';

/**
 * VerdictDisplay Component
 * Animated display of the AI verdict with scores and explanation
 * Includes PDF download functionality
 */
export default function VerdictDisplay({ result, onReset, language = 'en' }) {
  const contentRef = useRef(null);

  const labels = {
    en: {
      verdict: 'The Verdict',
      explanation: 'Analysis',
      personA: 'Person A',
      personB: 'Person B',
      newDispute: 'New Dispute',
      download: 'Download PDF'
    },
    fa: {
      verdict: 'حکم',
      explanation: 'تحلیل',
      personA: 'شخص الف',
      personB: 'شخص ب',
      newDispute: 'اختلاف جدید',
      download: 'دانلود PDF'
    }
  };

  const t = labels[language];
  const isRTL = language === 'fa';

  // Determine verdict icon and color
  const getVerdictStyle = () => {
    const { personA_score, personB_score } = result;
    const diff = Math.abs(personA_score - personB_score);
    
    if (diff <= 10) {
      return { 
        icon: Equal, 
        color: 'text-amber-600', 
        bg: 'bg-amber-50',
        border: 'border-amber-200'
      };
    }
    if (personA_score > personB_score) {
      return { 
        icon: CheckCircle2, 
        color: 'text-blue-600', 
        bg: 'bg-blue-50',
        border: 'border-blue-200'
      };
    }
    return { 
      icon: CheckCircle2, 
      color: 'text-purple-600', 
      bg: 'bg-purple-50',
      border: 'border-purple-200'
    };
  };

  const verdictStyle = getVerdictStyle();
  const VerdictIcon = verdictStyle.icon;

  // PDF Download handler
  const handleDownload = () => {
    const content = `
JUDGE - DISPUTE ANALYSIS REPORT
=====================================

VERDICT: ${result.verdict}

SCORES:
- Person A: ${result.personA_score}/100
- Person B: ${result.personB_score}/100

ANALYSIS:
${result.explanation}

=====================================
Generated by Judge
Date: ${new Date().toLocaleDateString()}
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'judge-verdict.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      className="w-full max-w-2xl mx-auto"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      dir={isRTL ? 'rtl' : 'ltr'}
      ref={contentRef}
    >
      {/* Verdict Header */}
      <motion.div
        className="text-center mb-10"
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        transition={{ duration: 0.5, delay: 0.2 }}
      >
        <div className="inline-flex items-center justify-center w-20 h-20 rounded-full bg-slate-800 mb-6 shadow-xl">
          <Scale className="w-10 h-10 text-amber-500" />
        </div>
        <h2 className="text-3xl md:text-4xl font-light text-slate-800 mb-2">
          {t.verdict}
        </h2>
      </motion.div>

      {/* Score Gauges */}
      <motion.div
        className="flex justify-center gap-12 md:gap-20 mb-10"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.4 }}
      >
        <ScoreGauge 
          score={result.personA_score} 
          label={t.personA}
          delay={0.5}
        />
        <ScoreGauge 
          score={result.personB_score} 
          label={t.personB}
          delay={0.7}
        />
      </motion.div>

      {/* Verdict Statement */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.9 }}
      >
        <Card className={`p-6 mb-6 ${verdictStyle.bg} ${verdictStyle.border} border-2`}>
          <div className="flex items-start gap-4">
            <div className={`p-2 rounded-full ${verdictStyle.bg}`}>
              <VerdictIcon className={`w-6 h-6 ${verdictStyle.color}`} />
            </div>
            <div className="flex-1">
              <h3 className="font-semibold text-slate-800 mb-1">
                {result.verdict}
              </h3>
            </div>
          </div>
        </Card>
      </motion.div>

      {/* Explanation */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 1.1 }}
      >
        <Card className="p-6 mb-8 bg-white border-slate-200">
          <h4 className="text-sm font-medium text-slate-500 uppercase tracking-wider mb-4">
            {t.explanation}
          </h4>
          <p className="text-slate-700 leading-relaxed">
            {result.explanation}
          </p>
        </Card>
      </motion.div>

      {/* Action Buttons */}
      <motion.div
        className="flex flex-col sm:flex-row gap-4 justify-center"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 1.3 }}
      >
        <Button
          onClick={onReset}
          variant="outline"
          className="h-12 px-6 border-slate-300 text-slate-700 hover:bg-slate-50"
        >
          <RotateCcw className={`w-4 h-4 ${isRTL ? 'ml-2' : 'mr-2'}`} />
          {t.newDispute}
        </Button>
        <Button
          onClick={handleDownload}
          className="h-12 px-6 bg-slate-800 hover:bg-slate-700 text-white"
        >
          <Download className={`w-4 h-4 ${isRTL ? 'ml-2' : 'mr-2'}`} />
          {t.download}
        </Button>
      </motion.div>
    </motion.div>
  );
}